### PR TITLE
ADAFRUIT HT16K33 Custom Character Generator

### PR DESCRIPTION
**Pull request by MCodez**
This code will help you to generate any custom character directly from the computer/machine. You have to design the character on the GUI and that code will be transferred to Arduino which will code the Display for that particular character. No need to hardcode different characters again and again.
Processing code will generate a GUI for BackPack and user has to create a custom character on GUI. Hitting the Run button will upload the code to Backpack and custom character will be displayed on the Led Matrix. Images are enclosed for reference.

Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:

- **Describe the scope of your change--i.e. what the change does and what parts
  of the code were modified.**  This will help us understand any risks of integrating
  the code.

- **Describe any known limitations with your change.**  For example, if the change
  doesn't apply to a supported platform of the library please mention it.

- **Please run any tests or examples that can exercise your modified code.**  We
  strive to not break users of the code and running tests/examples helps with this
  process.

Thank you again for contributing!  We will try to test and integrate the change
as soon as we can, but be aware we have many GitHub repositories to manage and
can't immediately respond to every request.  There is no need to bump or check in
on a pull request (it will clutter the discussion of the request).

Also, don't be worried if the request is closed or not integrated--sometimes the
priorities of Adafruit's GitHub code (education, ease of use) might not match the
priorities of the pull request.  Don't fret, the open source community thrives on
forks and GitHub makes it easy to keep your changes in a forked repo.

After reviewing the guidelines above you can delete this text from the pull request.

### CODE REVIEW

**Comment by MCodez** [comment]
Thanks,

Processing code is standalone and used to get software control on emoji. We
can use any GUI/Software which can send or receive serial data. Arduino is
receiving the serial data sent by the software, analyzing and printing
those emoticons on Backpack.

Regards
LALIT ARORA
UG Electronics and Communication
NSIT

**Comment by caternuson** [comment]
So the two work together? You'd have `custom character generator.ino` running on an Arduino board connected to a LED matrix. And then run `customgen.pde` and have that talk to the Arduino board running the sketch. That way you see the result live on the actual LED matrix?

**Comment by MCodez** [comment]
Done.

**Comment by MCodez** [comment]
Awesome, thanks!

Regards
LALIT ARORA
UG Electronics and Communication
NSIT

**Pull request merged**
