### PR TITLE
Add simple functions for turning the led display on and off.

### PR DESCRIPTION
**Pull request by djix123**
Useful for saving power on battery based applications.

### CODE REVIEW

**Comment by markfickett** [comment]
This looks handy. I'm working on a battery-powered setup and using a 7-segment LED for interactive output. Does this save power relative to just turning off all the LEDs (`sevenseg.clear(); sevenseg.setBrightness(0); sevenseg.writeDisplay();`)? At 5V, after calling those methods, I see a draw of 0.26mA; drawing even less would be great, but there's not a lot of room for improvement.

**Comment by MartinOrtel** [comment]
please accept this pull request.
this is basic power saving.
and 90% of the solution to issue #20

**Comment by bperrybap** [comment]
The ht16k33 brightness control uses 0-15 but 0 is not off.
It would have been nice to make the library API use 0 to 16 were 0 means off.
This would make the API more consistent with other library APIs used to set brightness & pwm output.
It would also eliminate the need for having API functions like displayOn() and displayOff() to turn the display on/off. Whille on/off display functions might be nice to have, if zero meant off, they wouldn't be needed to turn of the display as zero could mean turn it off.
However, it is not backward compatible with the existing API.

I have a locally modified version that works this way and it seems simpler than having to deal with 3 functions.
i.e. 1 function to set brightness, and two other functions to turn off the display and turn it back on.
It is simpler to just have a brightness of zero mean turn off the display.

I still think that if new 2 API functions to turn the display on/off are to be added, that displayOn() and displayOff() would be much better names than ledOn()/ledOff() names in the pull request.

**Comment by caternuson** [comment]
Can be done with `blinkRate()` using `HT16K33_BLINK_DISPLAYON` or `HT16K33_BLINK_OFF` 
https://adafruit.github.io/Adafruit_LED_Backpack/html/class_adafruit___l_e_d_backpack.html#a1149eda49278d0be6d86fdeca668f11b

**Pull request closed without merging**
