### PR TITLE
Update homepage URL

### PR DESCRIPTION
**Pull request by njh**

### CODE REVIEW

**Comment by njh** [comment]
Hi,

Is anything else needed in order to accept this Pull Request?

nick.

**Comment by njh** [comment]
Ping? This very simple pull request was opened nearly a year ago...

**Comment by caternuson** [comment]
The address seems to redirect OK?

**Comment by njh** [comment]
@caternuson redirects in web browser - just looking up Repo using the API can be problematic.

I am not sure why you didn't just merge the fix?
Was there an issue with the PR?

**Comment by caternuson** [comment]
We're just super careful about changing anything in `library.properties` to avoid breaking things with any Arduino Library Manager plumbing, etc. Changes made after registering the library repo can sometimes have unexpected effects. For example, `name` can't be changed on the fly.

We'll merge this and see what happens. If things break, we can revert.

**Comment by caternuson** [comment]
You'll need to push a new commit that includes current `library.properties` changes to resolve the merge conflict.

```
<<<<<<< patch-1
url=https://github.com/adafruit/Adafruit_LED_Backpack
=======
url=https://github.com/adafruit/Adafruit-LED-Backpack-Library
depends=Adafruit GFX Library, WaveHC, RTClib, Adafruit GPS Library
>>>>>>> master
```

**Comment by njh** [comment]
I have rebased my branch, so the merge conflict should be fixed now.

**Comment by caternuson** [comment]
yep. looks good. thanks for the fix.

**Pull request merged**
