### PR TITLE
Add segment name definitions for alphanumeric displays

### PR DESCRIPTION
**Pull request by jonnybergdahl**
I added segment name defines to make it easier for the user to use the alphanumeric display. I also added a simple animation that shows how to use the defines.

It makes it possible to write code like this - `alpha4.writeDigitRaw(0, ALPHANUM_SEG_C);`, which is way more readanle than  `alpha4.writeDigitRaw(0, 0c0004);`.

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
I didn't know where these segment names came from, in the .h file. It was only when I read the .ino example that I saw the link to the diagram. Could you add a comment to the .h file too?

```
... For segment names, 
// see https://learn.adafruit.com/14-segment-alpha-numeric-led-featherwing/usage

**Comment by dhalbert** [comment]
If you can do a diagram in ASCII in a comment, that would be even better.

**Comment by jonnybergdahl** [comment]
Good idea! Done.

**Review by dhalbert — APPROVED** [review]
This looks good to me, and doesn't change the actual running code anyway, so it's an easy safe change.

**Pull request merged**
