### PR TITLE
Add setDisplayState() to turn display on and off

### PR DESCRIPTION
**Pull request by jonnybergdahl**
Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:

- **Describe the scope of your change--i.e. what the change does and what parts
  of the code were modified.**  This will help us understand any risks of integrating
  the code.

I added a setState(bool state) call that you can use to turn the display on or off. 

- **Describe any known limitations with your change.**  For example if the change
  doesn't apply to a supported platform of the library please mention it.

The change exposes an existing command in the HT16K33 chip.

- **Please run any tests or examples that can exercise your modified code.**  We
  strive to not break users of the code and running tests/examples helps with this
  process.

This does not affect existing code.

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
Hi, `blinkRate()` is documented to do this already, with the appropriate arguments, and uses the same HT16K33 commands. From the .h file:
```c
  /*!
    @brief  Set display blink rate.
    @param  b  One of:
               HT16K33_BLINK_DISPLAYON = steady on
               HT16K33_BLINK_OFF       = steady off
               HT16K33_BLINK_2HZ       = 2 Hz blink
               HT16K33_BLINK_1HZ       = 1 Hz blink
               HT16K33_BLINK_HALFHZ    = 0.5 Hz blink
  */
  void blinkRate(uint8_t b);
```

**Comment by dhalbert** [comment]
OK, looking at the `blinkRate()` documentation, it's just wrong.

**Comment by jonnybergdahl** [comment]
Except the code does not actually do that, it makes sure it is on by hardcoding the ON value in the payload. 

`uint8_t buffer = HT16K33_BLINK_CMD | HT16K33_BLINK_DISPLAYON | (b << 1);`

Also - an on/off command does not really fit in a method named `blinkRate`, right?

I changed the comment to reflect what values you can actually use.

**Comment by dhalbert** [comment]
I was looking at this at midnight previously, sorry. My only comment then is that `setState()` is vague, since `state` could mean a lot of things.

I haven't found a really good name, but `setDisplayOn()`, `setIlluminated`, `setDisplayState`, are all candidates. Do you have a suggestion?

**Review by dhalbert — APPROVED** [review]
Good name, and I had no idea the brightness did not go to zero.

**Comment by jonnybergdahl** [comment]
I am working on finalizing this - https://github.com/jonnybergdahl/Arduino_JBWopr_Library
Found the brightness issue while doing the finals tests.

**Pull request merged**
